version: '3'
services:
  test1:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/brightcoin
    environment:
      - DOCKER_RUN_PORT=8081
  test2:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/brightcoin
    environment:
      - DOCKER_RUN_PORT=8080